

# mongo db container

volumes:
  data:

services:
  mongodb:
    image: mongo:latest
    volumes:
      - data:/data/db
    restart: always
    env_file: .env
    ports:
      - 27017:27017

  backend:
    build: backend
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
      - mongodb